//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECT.WebAPI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROYECT.WebAPI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROYECT - Aviso de Entrega de Trámite N° {0}.
        /// </summary>
        public static string Etiqueta_AvisoEntregaTramite {
            get {
                return ResourceManager.GetString("Etiqueta_AvisoEntregaTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROYECT - Informe del Estado del Tramite N° {0}&quot;.
        /// </summary>
        public static string Etiqueta_AvisoInformeEstadoTramite {
            get {
                return ResourceManager.GetString("Etiqueta_AvisoInformeEstadoTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROYECT - Aviso de Trámite Observado al Solicitante N° {0}.
        /// </summary>
        public static string Etiqueta_AvisoObservacionTramite {
            get {
                return ResourceManager.GetString("Etiqueta_AvisoObservacionTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROYECT - Aviso de Retiro de Trámite N° {0} al Solicitante .
        /// </summary>
        public static string Etiqueta_AvisoRetiroTramite {
            get {
                return ResourceManager.GetString("Etiqueta_AvisoRetiroTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspendido.
        /// </summary>
        public static string Etiqueta_FechaEntregaDocEnTramite {
            get {
                return ResourceManager.GetString("Etiqueta_FechaEntregaDocEnTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrumpida.
        /// </summary>
        public static string Etiqueta_FechaEntregaObservado {
            get {
                return ResourceManager.GetString("Etiqueta_FechaEntregaObservado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} debe ser menor que {1}.
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo CUIT/CUIL no contiene un CUIT/CUIL válido. Verifíquelo e ingréselo nuevamente.
        /// </summary>
        public static string Validacion_CuitCuilInvalido {
            get {
                return ResourceManager.GetString("Validacion_CuitCuilInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Estado del trámite no permite realizar la operación.
        /// </summary>
        public static string Validacion_EstadoTramiteInvalido {
            get {
                return ResourceManager.GetString("Validacion_EstadoTramiteInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha tiene un formato inválido..
        /// </summary>
        public static string Validacion_Fecha {
            get {
                return ResourceManager.GetString("Validacion_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha ingresada no está en el rango permitido.
        /// </summary>
        public static string Validacion_FechaMinima {
            get {
                return ResourceManager.GetString("Validacion_FechaMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede modificar Feriados anteriores a la fecha actual o dentro del plazo de días para los trámites.
        /// </summary>
        public static string Validacion_FechaNoEditable {
            get {
                return ResourceManager.GetString("Validacion_FechaNoEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} debe ser mayor que {1}.
        /// </summary>
        public static string Validacion_GreaterThan {
            get {
                return ResourceManager.GetString("Validacion_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} debe ser mayor o igual que {1}.
        /// </summary>
        public static string Validacion_GreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Validacion_GreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} no es valido.
        /// </summary>
        public static string Validacion_Invalid {
            get {
                return ResourceManager.GetString("Validacion_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jurisdicción invalida.
        /// </summary>
        public static string Validacion_InvalidJurisdiccion {
            get {
                return ResourceManager.GetString("Validacion_InvalidJurisdiccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una jurisdicción con la misma denominación para la provincia seleccionada.
        /// </summary>
        public static string Validacion_JurisdiccionDescripcionYaExiste {
            get {
                return ResourceManager.GetString("Validacion_JurisdiccionDescripcionYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su jurisdicción no está habilitada para ingresar al sistema..
        /// </summary>
        public static string Validacion_JurisdiccionInhabilitada {
            get {
                return ResourceManager.GetString("Validacion_JurisdiccionInhabilitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una jurisdicción para la localidad seleccionada.
        /// </summary>
        public static string Validacion_JurisdiccionLocalidad {
            get {
                return ResourceManager.GetString("Validacion_JurisdiccionLocalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya Existe una jurisdiccion para la provincia seleccionada.
        /// </summary>
        public static string Validacion_JurisdiccionProvincia {
            get {
                return ResourceManager.GetString("Validacion_JurisdiccionProvincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una jurisdiccion con la misma sigla.
        /// </summary>
        public static string Validacion_JurisdiccionSiglaYaExiste {
            get {
                return ResourceManager.GetString("Validacion_JurisdiccionSiglaYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} debe ser menor o igual que {1}.
        /// </summary>
        public static string Validacion_LessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Validacion_LessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las liquidaciones seleccionadas no sumarizan un valor correcto para compensar..
        /// </summary>
        public static string Validacion_LiquidacionesSumarizadas {
            get {
                return ResourceManager.GetString("Validacion_LiquidacionesSumarizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquidación inválida..
        /// </summary>
        public static string Validacion_LiquidacionInvalida {
            get {
                return ResourceManager.GetString("Validacion_LiquidacionInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensación Inválida. Para poder compensar estas liquidaciones, debe resolver las liquidaciones pendientes existentes..
        /// </summary>
        public static string Validacion_LiquidacionInvalida_ExistenOtras {
            get {
                return ResourceManager.GetString("Validacion_LiquidacionInvalida_ExistenOtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La localidad no pertenece a la provincia seleccionada.
        /// </summary>
        public static string Validacion_LocalidadProvincia {
            get {
                return ResourceManager.GetString("Validacion_LocalidadProvincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La {0} indicada no existe.
        /// </summary>
        public static string Validacion_NoExisteElementoA {
            get {
                return ResourceManager.GetString("Validacion_NoExisteElementoA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {0} indicado no existe.
        /// </summary>
        public static string Validacion_NoExisteElementoB {
            get {
                return ResourceManager.GetString("Validacion_NoExisteElementoB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no está habilitado para ingresar al sistema..
        /// </summary>
        public static string Validacion_NoHabilitadoASistema {
            get {
                return ResourceManager.GetString("Validacion_NoHabilitadoASistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plazo del Tramite cerrardo anteriormente.
        /// </summary>
        public static string Validacion_PlazoCerrado {
            get {
                return ResourceManager.GetString("Validacion_PlazoCerrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Fecha de Vigencia Desde se superpone con el periodo de vigencia del Tipo de Plazo de Trámite anterior.
        /// </summary>
        public static string Validacion_PlazoVigenciaDesdeDentroDePeriodoInvalido {
            get {
                return ResourceManager.GetString("Validacion_PlazoVigenciaDesdeDentroDePeriodoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un elemento que cumple con los parámetros enviados.
        /// </summary>
        public static string Validacion_RegistroYaExiste {
            get {
                return ResourceManager.GetString("Validacion_RegistroYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} es requerido.
        /// </summary>
        public static string Validacion_Requerido {
            get {
                return ResourceManager.GetString("Validacion_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no está asignado a ninguna jurisdicción.
        /// </summary>
        public static string Validacion_SinJurisdiccionAsignada {
            get {
                return ResourceManager.GetString("Validacion_SinJurisdiccionAsignada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud máxima del campo {0} es de {1} caracteres.
        /// </summary>
        public static string Validacion_TamanoMaximo {
            get {
                return ResourceManager.GetString("Validacion_TamanoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Fecha de Vigencia Desde se superpone con el periodo de vigencia de la tasa PROYECT anterior.
        /// </summary>
        public static string Validacion_TasaNacionalVigenciaDesdeDentroDePeriodoInvalido {
            get {
                return ResourceManager.GetString("Validacion_TasaNacionalVigenciaDesdeDentroDePeriodoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha configurado matrícula o tomo y folio correctamente o, existe un conflicto en su configuración. Recuerde que almenos una debe ser obligatoria..
        /// </summary>
        public static string Validacion_TramiteDatoMatriculaConflico {
            get {
                return ResourceManager.GetString("Validacion_TramiteDatoMatriculaConflico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los requerimientos en nomenclatura catastral difieren entre si. Esta configuración es conjunta y deberían ser configurados con la misma condición..
        /// </summary>
        public static string Validacion_TramiteDatoNomenclatura {
            get {
                return ResourceManager.GetString("Validacion_TramiteDatoNomenclatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alguno de los elementos enviados no tiene asignada una condición o la misma es inexistente.
        /// </summary>
        public static string Validacion_TramiteDatoParametroCondicionFaltante {
            get {
                return ResourceManager.GetString("Validacion_TramiteDatoParametroCondicionFaltante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de trámite requiere mas datos de configuración que los enviados..
        /// </summary>
        public static string Validacion_TramiteDatoParametroFaltante {
            get {
                return ResourceManager.GetString("Validacion_TramiteDatoParametroFaltante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alguno de los elementos enviados excede el tamaño máximo para el nombre.
        /// </summary>
        public static string Validacion_TramiteDatoParametroLabelExcede {
            get {
                return ResourceManager.GetString("Validacion_TramiteDatoParametroLabelExcede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alguno de los elementos enviados no tiene asignado un nombre.
        /// </summary>
        public static string Validacion_TramiteDatoParametroLabelFaltante {
            get {
                return ResourceManager.GetString("Validacion_TramiteDatoParametroLabelFaltante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tomo y el folio deben ser configurados con la misma condicion..
        /// </summary>
        public static string Validacion_TramiteDatoTomoFolioConflicto {
            get {
                return ResourceManager.GetString("Validacion_TramiteDatoTomoFolioConflicto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario o contraseña son incorrectos.
        /// </summary>
        public static string Validacion_UsuarioIncorrecto {
            get {
                return ResourceManager.GetString("Validacion_UsuarioIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario puede tener solamente una (1) jurisdicción asignada.
        /// </summary>
        public static string Validacion_UsuarioMasDeUnaJurisdiccionAsignada {
            get {
                return ResourceManager.GetString("Validacion_UsuarioMasDeUnaJurisdiccionAsignada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no tiene permiso para eliminar {0}.
        /// </summary>
        public static string Validacion_UsuarioNoPuedeEliminar {
            get {
                return ResourceManager.GetString("Validacion_UsuarioNoPuedeEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no tiene permiso para modificar {0}.
        /// </summary>
        public static string Validacion_UsuarioNoPuedeHacerCambios {
            get {
                return ResourceManager.GetString("Validacion_UsuarioNoPuedeHacerCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no tiene permiso para obtener {0}.
        /// </summary>
        public static string Validacion_UsuarioNoPuedeObtener {
            get {
                return ResourceManager.GetString("Validacion_UsuarioNoPuedeObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} no es una fecha valida.
        /// </summary>
        public static string Validacion_ValidDate {
            get {
                return ResourceManager.GetString("Validacion_ValidDate", resourceCulture);
            }
        }
    }
}
